version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
    - echo "Build started"
  post_build:
    commands:
    - echo "Build completed"
    - mvn package
    - mv target/LambdaDemo1-0.0.1-SNAPSHOT.jar LambdaDemo1-0.0.1-SNAPSHOT.jar
artifacts:
  files:
  - LambdaDemo1-0.0.1-SNAPSHOT.jar
  - .ebextensions/**/*
