version: 0.2
phases:
 build:
  commands:
   - echo "This is build phase"
   - zip -r deployment_package.zip . -i lambda_function.java
   #- mvn clean package
post_build:
 commands:
   - echo "Deploying to the Lambda"
   - aws lambda update-function-code --function-name lambda1 --zip-file fileb://deployment_package.zip
  artifacts:
   type: zip
   paths: 
       - "*"
